# Generated by Django 3.0.7 on 2020-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
