# Generated by Django 3.0.7 on 2020-06-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='field_name',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
